version: '3'

services:
  app:
    build: .
    container_name: ${CONTAINER_NAME}
    ports:
      - "${HOST_APP_PORT}:${CONTAINER_APP_PORT}"
    command: ./cmd/start-container-dev-app.sh
    volumes:
      - .:/home/python/app