
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Stefano Oliveira", email = "oliveira.stefano@gmail.com"},
]
dependencies = []
requires-python = ">=3.10"
license = {text = "MIT"}

[tool.pdm.dev-dependencies]
dev = [
    "autopep8>=2.0.2",
    "pylint>=2.17.4",
]